name: Trigger JitPack Build

on:
  release:
    types: [published]

jobs:
  jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger JitPack build
        run: |
          STATUS_URL="https://jitpack.io/api/builds/com.github.pingpongboss/compose-exploded-layers/${{ github.event.release.tag_name }}"
          LOG_URL="https://jitpack.io/com/github/pingpongboss/compose-exploded-layers/${{ github.event.release.tag_name }}/build.log"

          echo "Streaming build logs at: ${LOG_URL}"
          echo

          while true; do
            echo "Checking status..."
            STATUS=$(curl -s "$STATUS_URL" | jq -r '.status')
            echo "Status is: $STATUS"
            
            [[ "$STATUS" == "ok" || "$STATUS" == "Error" ]] && break

            echo "Checking again in 2 minutes"
            echo "----------------------------------------------"
            sleep 120
          done

          echo "Final build status: ${STATUS}"
          echo "View build logs at: ${LOG_URL}"

          if [ "$STATUS" != "ok" ]; then
            echo "❌ JitPack build failed"
            exit 1
          fi

          echo "✅ JitPack build succeeded"
