name: Trigger JitPack Build

on:
  release:
    types: [published]

jobs:
  jitpack:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger JitPack build
        run: |
          API_URL="https://jitpack.io/api/builds/com.github.pingpongboss/compose-exploded-layers/${{ github.event.release.tag_name }}"

          echo "Triggering JitPack build for ${REPO}:${TAG}"
          curl -s "${API_URL}" > /dev/null
          echo "Build triggered. Waiting for logs..."

      - name: Stream JitPack build log
        run: |
          LOG_URL="https://jitpack.io/com/github/pingpongboss/compose-exploded-layers/${{ github.event.release.tag_name }}/build.log"
          STATUS_URL="https://jitpack.io/api/builds/com.github.pingpongboss/compose-exploded-layers/${{ github.event.release.tag_name }}"

          echo "Streaming build logs from: ${LOG_URL}"
          echo

          # Poll the log every 5 seconds until the build finishes
          STATUS="building"
          while [[ "$STATUS" != "ok" && "$STATUS" != "Error" ]]; do
            curl -s "${LOG_URL}" | tail -n 20
            echo "----------------------------------------------"
            STATUS=$(curl -s "${STATUS_URL}" | jq -r '.status')
            echo "Current status: ${STATUS}"
            sleep 10
          done

          echo "----------------------------------------------"
          echo "Final build status: ${STATUS}"

          if [ "$STATUS" != "ok" ]; then
            echo "❌ JitPack build failed"
            exit 1
          fi

          echo "✅ JitPack build succeeded"
