name: Build and Upload Android Sample APK

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag name to upload Android APK to (e.g. 1.1.2)"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag || github.event.release.tag_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build Android sample debug APK
        run: ./gradlew :samples:android:assembleDebug

      - name: Rename APK
        run: |
          mv samples/android/build/outputs/apk/debug/android-debug.apk samples/android/build/outputs/apk/debug/android-sample-debug-${{ github.event.inputs.tag || github.event.release.tag_name }}.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: samples/android/build/outputs/apk/debug/android-sample-debug-${{ github.event.inputs.tag || github.event.release.tag_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
