name: Build and Upload Sample APK

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Build sample debug APK
        run: ./gradlew :sample:assembleDebug

      - name: Rename APK
        run: |
          mv sample/build/outputs/apk/debug/sample-debug.apk sample/build/outputs/apk/debug/sample-debug-${{ github.event.release.tag_name }}.apk

      - name: Upload APK to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: sample/build/outputs/apk/debug/sample-debug-${{ github.event.release.tag_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
